name: Hello Workflow

on:
  workflow_dispatch: # lets you run it manually from Actions tab

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from GitHub Actions 🚀"
